# Generated by Django 2.1.3 on 2019-01-13 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others/Unknown', 'Others/Unknown')], max_length=100)),
                ('description', models.TextField()),
                ('is_immortal', models.BooleanField(default=True)),
                ('benevolence_factor', models.PositiveSmallIntegerField(help_text='How benevolent this hero is?')),
                ('arbitrariness_factor', models.PositiveSmallIntegerField(help_text='How arbitrary this hero is?')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='hero_headshots/')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Category')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='entities.Hero')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entities.Hero')),
            ],
            options={
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='HeroAcquaintance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entities.Category')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others/Unknown', 'Others/Unknown')], max_length=100)),
                ('description', models.TextField()),
                ('is_immortal', models.BooleanField(default=False)),
                ('malevolence_factor', models.PositiveSmallIntegerField(help_text='How malevolent this villain is?')),
                ('power_factor', models.PositiveSmallIntegerField(help_text='How powerful this villain is?')),
                ('is_unique', models.BooleanField(default=True)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Category')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Origin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Origin'),
        ),
        migrations.AddField(
            model_name='hero',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entities.Hero'),
        ),
    ]
