# Generated by Django 2.1.3 on 2018-11-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_heroacquaintance'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroacquaintance',
            name='friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entities.HeroAcquaintance'),
        ),
    ]
