# Generated by Django 2.1.3 on 2018-11-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_heroacquaintance_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroacquaintance',
            name='friends',
        ),
    ]
