# Generated by Django 2.1.3 on 2018-11-07 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_remove_heroacquaintance_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroacquaintance',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entities.Category'),
        ),
    ]
